var_poc:
  target: dev
  outputs:
    # 開発環境（TD検証用）
    dev:
      type: snowflake
      private_key_path: "{{ env_var('DEV_SNOWFLAKE_PRIVATE_KEY') }}"
      account: "{{ env_var('DEV_ACCOUNT') }}"
      user: "{{ env_var('DEV_SNOW_USER') }}"
      role: "{{ env_var('DEV_ROLE') }}"
      database: "{{ env_var('DEV_DB') }}"
      warehouse: "{{ env_var('DEV_WAREHOUSE') }}"
      schema: "{{ env_var('DEV_SCHEMA') }}"
      threads: 1
